'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";
import SubSidebar from "./sub-sidebar";
import { Provider } from "react-redux";
import { makeStore } from "@/redux/app/store";
import { Box, CssBaseline, Drawer, IconButton, Typography } from "@mui/material";
import { Icon } from "@iconify/react";
import MainApp from "@/component/main-app";
import { MilkdownProvider } from "@milkdown/react";
import { useState } from "react";
import Bottombar from "./bottombar";
import { useAppSelector } from "@/redux/app/hooks";
import { Folder } from "@/component/mobile/folders/folders";
import Topbar from "./topbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"/>
      </head>
      <body className={inter.className}>
        <CssBaseline />
        <Provider store={makeStore()}>
          <MilkdownProvider>
            <Topbar />

            <div style={{height: 'calc(100dvh - 100px)', backgroundColor: '#f0f2f7'}}>
              { children }
            </div>

            <Bottombar />
          </MilkdownProvider>
        </Provider>
      </body>
    </html>
  );
}
