'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";
import SubSidebar from "./sub-sidebar";
import { Provider } from "react-redux";
import { makeStore } from "../redux/app/store";
import { Box, CssBaseline, IconButton } from "@mui/material";
import { Icon } from "@iconify/react";
import MainApp from "@/component/main-app";
import { MilkdownProvider } from "@milkdown/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <Provider store={makeStore()}>
          <MilkdownProvider>
            <MainApp>
              {children}
            </MainApp>
          </MilkdownProvider>
        </Provider>
      </body>
    </html>
  );
}
