'use client'
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { makeStore } from "@/redux/app/store";
import { CssBaseline } from "@mui/material";
import styles from "./layout.module.css"
import Topbar from "@/component/todo/topbar";
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { Viewport } from "next";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        {/* <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, interactive-widget=resizes-content' /> */}
      </head>
      <body className={`${inter.className} ${styles.body}`} >
        <CssBaseline />
        <Provider store={makeStore()}>
          <LocalizationProvider dateAdapter={AdapterDayjs}>
            <Topbar />
            {children}
          </LocalizationProvider>
        </Provider>
      </body>
    </html>
  );
}
